### ISSUE TITLE
Unable to start component:  'list' object has no attribute 'split'

### ISSUE THREAD

**Issue by hathalud** [rodpayne/home-assistant_person_location#1]
After adding this component to HA from HACS and restarting my HA, I am not finding the option to add Person Location in the list of options to setup a new integration. 

After bouncing over to my ssh session and editing the configuration.yaml file and restarting HA, the following error is encountered.

Error during setup of component person_location
4:08:32 AM – (ERROR) Person Location (custom integration)
```
Logger: homeassistant.setup
Source: custom_components/person_location/const.py:270
Integration: Person Location (documentation, issues)
First occurred: 4:08:32 AM (1 occurrences)
Last logged: 4:08:32 AM
```

```
Error during setup of component person_location
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 249, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/person_location/__init__.py", line 41, in setup
    pli = PERSON_LOCATION_INTEGRATION(API_STATE_OBJECT, hass, config)
  File "/config/custom_components/person_location/const.py", line 270, in __init__
    for x in self.config[DOMAIN].get(CONF_CREATE_SENSORS, []).split(",")
AttributeError: 'list' object has no attribute 'split'
```

I thought maybe it was caused by including my device tracker from room-assistant for my galaxy watch and commented that line out and restarted HA. It had no affect. I then went and added the Google api key and restarted. Still no effect. Last of all I commented out the "person." devices and gave HA a restart. Still no success starting this integration with no change on the error message given.

```
person_location:
  google_api_key: ***redacted**
  person_names:
    - name: Hath
      devices:
        - device_tracker.haths_s21
#        - device_tracker.haths_galaxy_watch_tracker
#        - person.hathakhm
    - name: Kyra
      devices:
#        - person.kyra
        - device_tracker.kyra_s_s21_ultra
```

**Comment by rodpayne** [comment]
Sorry, I haven't gotten back to this for a while.  This error was exposed whenever `create_sensors` was missing in the yaml configuration.  The code was corrected on June 27th, but I neglected to create a new release containing it.  I did that tonight.

**Comment by hathalud** [comment]
It eventually started working a week or two ago. I think I had to restart the server, not just the HA Docker container. 

As of yet, I haven't understood how to use this addon yet. I'm smart, but autistic, so I have trouble understanding what others pick up instantly because it was inferred information not explicit information. Could you help me understand it better please?

**Comment by rodpayne** [comment]
Take a look in the `States` tab of `Developer Tools`. Do you have entities named `sensor.hath_location` and `sensor.kyra_location`?  These should show the results of the reverse geocoding.   

If they are not there, take a look in `Logs` under `Configuration` to see if there are any errors or warnings related to the integration.

If they are there, this is the basic information available from the integration.  They can be added to Lovelace to show the current location.  If there are particular attributes that you are interested in, additional sensors can be created by adding something like `create_sensors: bread_crumbs,driving_miles,driving_minutes,geocoded,miles_from_home` to the configuration.

You can also see if the integration is running by going to `Configuration`, `Server Controls`, then click the `Info` tab and look for `Person Location` in the `System Health`.

![image](https://user-images.githubusercontent.com/28266684/132951830-2b207795-e371-4958-852a-9c6ad12eb328.png)
