### ISSUE TITLE
Orphaned and unremovable integration

### ISSUE THREAD

**Issue by Construct-Ent** [rodpayne/home-assistant_person_location#11]
i gave this a test drive, decided it wasn't what i was looking for and now i have it showing as an integration and it erros as not loaded all the time and i am unable to remove the integration. my only option is to leave it in the back ground and disable it. even if i remove it from teh HACS screen the integration screen still shows it as errored .

**Comment by Construct-Ent** [comment]
Setup failed for custom integration person_location: Unable to import component: No module named 'WazeRouteCalculator'
7:46:54 PM – (ERROR) person_location (custom integration)

**Comment by Insane0923** [comment]
Same problem here.
The integration worked ok, until I update HA to ver 2023.9

**Comment by rodpayne** [comment]
There is a 2023.09.07 version in pre-release.  If someone could check it out, I'll take it out of pre-release if it gets rid of the error. (Based on previous experience, I'm waiting for 2023.9.1+ before doing my own upgrade.)

________________________________

**Comment by Construct-Ent** [comment]
the Beta seems to have fixed it not starting correctly, and allowed it to be removed, so looks like it did the job, Thanks.

**Comment by sbelongie** [comment]
tested the pre-release and it works fine for me.

**Comment by Insane0923** [comment]
It works fine also for me. Thank you !

**Comment by rodpayne** [comment]
Thank you for everyone's help in checking this out... and to Jack for coding the correction.
