### ISSUE TITLE
Error trying to use this with 2022.2.3

### ISSUE THREAD

**Issue by jackyaz** [rodpayne/home-assistant_person_location#2]
GUI flow fails to load via Integrations menu. When attempting manual configuration in yaml, check configuration throws the below error
```
Component error: person_location - cannot import name 'REGIONS' from 'homeassistant.components.waze_travel_time.sensor' (/usr/src/homeassistant/homeassistant/components/waze_travel_time/sensor.py)
```

**Comment by rodpayne** [comment]
Release Version 2022.02.09 should resolve the problem with Core 2022.2.3.  (Tested on 2022.2.5.)

**Comment by jackyaz** [comment]
Thank you for the swift fix! Looking forward to trying this out now :)
