### ISSUE TITLE
Waze Exception WRCError: Internal Error

### ISSUE THREAD

**Issue by swa72** [rodpayne/home-assistant_person_location#5]
I’m on 2022.6.4 and getting …

```
This error originated from a custom integration.

Logger: custom_components.person_location.reverse_geocode
Source: custom_components/person_location/reverse_geocode.py:837 
Integration: Person Location (documentation, issues) 
First occurred: 8 June 2022, 09:32:23 (68 occurrences) 
Last logged: 8 June 2022, 22:19:29

(sensor.aaa_location) Waze Exception WRCError: Internal Error
(sensor.bbb_location) Waze Exception WRCError: Internal Error
(sensor.ccc_location) Waze Exception WRCError: Internal Error
```
It may be related to https://github.com/home-assistant/core/issues/22022#issuecomment-675623793 or https://github.com/home-assistant/core/issues/22022#issuecomment-683247756.

**Comment by jackyaz** [comment]
I see this error too

**Comment by rodpayne** [comment]
Is anyone still getting these?  (I sure hope not, after a year.)  I think that these may show up from time to time because of unexpected responses from the Waze servers.

**Comment by rodpayne** [comment]
If we have to come back to it, a retry of the Waze call may be in order.  
See https://github.com/home-assistant/core/issues/22022#issuecomment-675782947.
