### ISSUE TITLE
Unclear on what follow_person_integration does

### ISSUE THREAD

**Issue by jackyaz** [rodpayne/home-assistant_person_location#6]
I'm not sure what the follow_person_integration setting does. I track Person entities with this integration, which have a combination of static and GPS trackers attached

Should I enable follow_person_integration ?

**Comment by rodpayne** [comment]
Short answer:  yes.

One of the `person_location` integration's functions is to look at all device trackers (`devices` in the configuration) that are under a particular person (`name` in the configuration) and combine them into a single person location sensor.  This is also a function that is done by the `person` integration, but with a different algorithm.  If you favor the algorithm that the person integration uses, you can specify the person entity for `devices` configured for the person_location integration.  For example:  

```
person_location:
  person_names:
    - name: Pam
      devices: person.pam
```
If you want to do that for all of the people entities, then the `follow_person_integration` option should do that for you without specifying all of them individually in the configuration.

**Comment by rodpayne** [comment]
Hopefully this was enough to answer your question and that everything is going well for you.
