### ISSUE TITLE
Setup failed for custom integration person_location: Unable to import component: No module named 'WazeRouteCalculator'

### ISSUE THREAD

**Issue by jackyaz** [rodpayne/home-assistant_person_location#9]
Setup failed for custom integration person_location: Unable to import component: No module named 'WazeRouteCalculator'

2023.9

**Comment by rodpayne** [comment]
There is a 2023.09.07 version in pre-release.  If someone could check it out, I'll take it out of pre-release if it gets rid of the error. (Based on previous experience, I'm waiting for 2023.9.1+ before doing my own upgrade.)


From: Jack ***@***.***>
Sent: Wednesday, September 6, 2023 4:46 PM
To: rodpayne/home-assistant_person_location ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rodpayne/home-assistant_person_location] Setup failed for custom integration person_location: Unable to import component: No module named 'WazeRouteCalculator' (Issue #9)


Setup failed for custom integration person_location: Unable to import component: No module named 'WazeRouteCalculator'

2023.9

**Comment by jackyaz** [comment]
2023.9.1 just dropped so hopefully you can check if my swap works for 100% of cases

**Comment by rodpayne** [comment]
I merged it, tried it, and it is now released as Version 2023.09.08.  Thank you for your help.
